(use-package dired
  :config
  (defvar dired-vc-status-overlays nil
    "List of active overlays in Dired for Git status.")
  (defun dired--vc-status-face (code)
    "Return a cons cell (STATUS . FACE) for a given Git porcelain CODE."
    (let* ((vc-status-untracked "??")
           (vc-status-modified " M")
           (vc-status-modified-alt "M ")
           (vc-status-deleted "D ")
           (vc-status-added "A ")
           (vc-status-renamed "R ")
           (vc-status-copied "C ")
           (vc-status-ignored "!!")
           (status (cond
                    ((string-match-p "\\?\\?" code) vc-status-untracked)
                    ((string-match-p "^ M" code) vc-status-modified)
                    ((string-match-p "^M " code) vc-status-modified-alt)
                    ((string-match-p "^D" code) vc-status-deleted)
                    ((string-match-p "^A" code) vc-status-added)
                    ((string-match-p "^R" code) vc-status-renamed)
                    ((string-match-p "^C" code) vc-status-copied)
                    ((string-match-p "\\!\\!" code) vc-status-ignored)
                    (t "  ")))
           (face (cond
                  ((string= status vc-status-ignored) 'shadow)
                  ((string= status vc-status-untracked) 'warning)
                  ((string= status vc-status-modified) 'font-lock-function-name-face)
                  ((string= status vc-status-modified-alt) 'font-lock-function-name-face)
                  ((string= status vc-status-deleted) 'error)
                  ((string= status vc-status-added) 'success)
                  (t 'font-lock-keyword-face))))
      (cons status face)))
  (defun dired-vc-status-overlay ()
    "Overlay VC status indicators on the first column in Dired."
    (interactive)
    (let ((vc-root (ignore-errors (vc-root-dir))))
      (when (and vc-root (not (file-remote-p default-directory)))
        (setq vc-root (expand-file-name vc-root))
        (let ((vc-status (vc-dir-status-files vc-root))
              ;; (vc-git--run-command-string nil "status" "--porcelain" "--ignored" "--untracked-files=normal"))
              (status-map (make-hash-table :test 'equal)))
          (mapc #'delete-overlay dired-vc-status-overlays)
          (setq dired-vc-status-overlays nil)
          (dolist (line (split-string vc-status "\n" t))
            (when (string-match "^\\(..\\) \\(.+\\)$" line)
              (let* ((code (match-string 1 line))
                     (file (match-string 2 line))
                     (fullpath (expand-file-name file vc-root))
                     (status-face (dired-vc-status-face code)))
                (puthash fullpath status-face status-map))))
          (save-excursion
            (goto-char (point-min))
            (while (not (eobp))
              (let* ((file (ignore-errors (expand-file-name (dired-get-filename nil t)))))
                (when file
                  (setq file (if (file-directory-p file) (concat file "/") file))
                  (let* ((status-face (gethash file status-map (cons "  " 'font-lock-keyword-face)))
                         (status (car status-face))
                         (face (cdr status-face))
                         (status-str (propertize (format " %s " status) 'face face))
                         (ov (make-overlay (line-beginning-position) (1+ (line-beginning-position)))))
                    (overlay-put ov 'before-string status-str)
                    (push ov dired-vc-status-overlays))))
              (forward-line 1)))))))
  :hook (dired-after-readin . dired-vc-status-overlay))
